### ISSUE TITLE
the note type having the only picture

### ISSUE THREAD

**Issue by KIMYONGUP** [krassowski/Anki-TouchScreen#4] opened 2018-12-19 11:30 UTC
we cannot write on the note type of enhanced image occlusion
can you fix it?

**Comment by krassowski** [comment] 2018-12-19 11:38
Hi @KIMYONGUP. It would help greatly if you could write more about your problem, so it can be understood and fixed. It would be ideal if you could provide a screenshot/picture and step-by-step reproduction instruction.

**Comment by krassowski** [comment] 2019-04-20 18:59
Closing as duplicate of #5. Please feel to re-open if you feel that this was not addressed in #5.

**Closed as completed by krassowski** 2019-04-20 18:59 UTC

**Comment by KIMYONGUP** [comment] 2019-04-21 05:59
Wow. Thanks! It's so touching. Actually I didn't expect you to fix the
problem, but you did it!! so thanks! Now I am able to  write on image
occlusion card! thanks a lot!!!!

2019년 4월 21일 (일) 오전 3:59, M. Krassowski <notifications@github.com>님이 작성:
